/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/files': {
    get: operations['FilesController_findAll'];
    post: operations['FilesController_create'];
  };
  '/files/{id}': {
    get: operations['FilesController_findOne'];
    delete: operations['FilesController_remove'];
    patch: operations['FilesController_update'];
  };
  '/auth/apple': {
    post: operations['AuthController_apple'];
  };
  '/auth/me': {
    get: operations['AuthController_me'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    UpdateFileDto: Record<string, never>;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {
  FilesController_findAll: {
    responses: {
      200: never;
    };
  };
  FilesController_create: {
    responses: {
      201: never;
    };
  };
  FilesController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: never;
    };
  };
  FilesController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: never;
    };
  };
  FilesController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateFileDto'];
      };
    };
    responses: {
      200: never;
    };
  };
  AuthController_apple: {
    responses: {
      201: never;
    };
  };
  AuthController_me: {
    responses: {
      200: never;
    };
  };
}
